### ISSUE TITLE
note: the lang item is first defined in crate `std` (which `serde` depends on)

### ISSUE THREAD

**Issue by GopherJ** [risc0/risc0#1075]
```toml
[dependencies]
pxp-primitives = { path = "../../primitives", default-features = false, features = [] }
risc0-zkvm     = { version = "0.18", default-features = false, features = [] }

[patch.crates-io]
radium = { git = 'https://github.com/ferrilab/radium.git', rev = "723bed5" }
# use optimized risc0 circuit
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.2-risczero.0" }
k256          = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "k256/v0.13.1-risczero.1" }
sha2          = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.6-risczero.0" }

[features]
default = []
std     = ["pxp-primitives/std", "risc0-zkvm/std"]

```

I try to use no_std of risc0-zkvm, my own crate implemented no_std as well but it paniced
