### ISSUE TITLE
[BUG] 'failed to fill whole buffer' error when using k256 crate

### ISSUE THREAD

**Issue by conduition** [risc0/risc0#1455]
## Bug Report

When using [the `k256` crate](https://crates.io/crates/k256) - a pure Rust secp256k1 implementation - in the zkVM guest, the guest program executes OK, but `prover.prove` returns an error on the host side: `failed to fill whole buffer`

```console
$ cargo run .
proving execution...
thread 'main' panicked at host/src/main.rs:28:10:
failed to prove: failed to fill whole buffer
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Following the backtrace, the error seems to originate from the `ark-std` crate, in `src/io/mod.rs`. I am currently waiting for risc0 to reinstall. Once it does I will provide a full backtrace.

If I comment out the two critical lines in the guest crate's code, the proof runs OK, except obviously the elliptic curve point output is not written to the journal anymore.

```diff
diff --git a/methods/guest/src/main.rs b/methods/guest/src/main.rs
index 78e7b81..a2a905f 100644
--- a/methods/guest/src/main.rs
+++ b/methods/guest/src/main.rs
@@ -25,8 +25,8 @@ fn main() {
 
     // Compute the public key of the given input.
     // Uncommenting these lines out will cause the host to panic.
-    let point = secp256k1_ec_mul(&input);
-    output[32..].copy_from_slice(&point);
+    // let point = secp256k1_ec_mul(&input);
+    // output[32..].copy_from_slice(&point);
 
     let output_bytes: &[u8] = output.as_ref();
     env::commit(&output_bytes);
```

```console
$ cargo run .
proving execution...
receipt journal output:
  hash:  72cd6e8422c407fb6d098690f1130b7ded7ec2f7f5e1d30bd9d521f015363793
  point: 000000000000000000000000000000000000000000000000000000000000000000
verifying receipt...
OK
```

## Steps to Reproduce

1. I followed the instructions [here](https://dev.risczero.com/api/zkvm/install) to install the risc0 tools and toolchain.
2. I set up a simple ZK key-statement proof which asserts than a given hash preimage is also the secret key to some public key on the secp256k1 curve. [The full code is here](https://github.com/conduition/zkpreimage), but i'll also include the guest and host code below.

<details>
<summary><h3>Guest</h3></summary>

```rust
#![no_main]
#![no_std]

use k256::elliptic_curve::group::GroupEncoding as _;
use risc0_zkvm::guest::env;
use risc0_zkvm::sha;
use sha::Sha256 as _;

risc0_zkvm::guest::entry!(main);

#[allow(dead_code)]
fn secp256k1_ec_mul(secret: &[u8; 32]) -> [u8; 33] {
    let seckey = k256::SecretKey::from_bytes(secret.into()).expect("secret key is invalid");
    let pubkey = seckey.public_key();
    pubkey.as_affine().to_bytes().into()
}

fn main() {
    let input: [u8; 32] = env::read();
    let mut output = [0u8; 32 + 33];

    // Compute SHA256 hash, and write it to the journal as a public output
    let digest = sha::Impl::hash_bytes(&input);
    output[..32].copy_from_slice(digest.as_bytes());

    // Compute the public key of the given input.
    // Uncommenting these lines out will cause the host to panic.
    let point = secp256k1_ec_mul(&input);
    output[32..].copy_from_slice(&point);

    let output_bytes: &[u8] = output.as_ref();
    env::commit(&output_bytes);
}
```

Cargo.toml:

```toml
[package]
name = "provable_sha256_dlog"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
# If you want to try (experimental) std support, add `features = [ "std" ]` to risc0-zkvm
risc0-zkvm = { version = "1.0.1", default-features = false, features = [] }
k256 = { version = "0.13.3", default-features = false, features = ["arithmetic", "serde"] }
```

</details>

<details>
<summary><h3>Host</h3></summary>

```rust
// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{PROVABLE_SHA256_DLOG_ELF, PROVABLE_SHA256_DLOG_ID};
use risc0_zkvm::{default_prover, ExecutorEnv};

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    // Arbitrary input.
    let input = [1u8; 32];

    let env = ExecutorEnv::builder()
        .write(&input)
        .unwrap()
        .build()
        .unwrap();

    // Obtain the default prover.
    let prover = default_prover();

    // Produce a receipt by proving the specified ELF binary.
    println!("proving execution...");
    let receipt = prover
        .prove(env, PROVABLE_SHA256_DLOG_ELF)
        .expect("failed to prove"); // <-------- CRASH HERE

    // Parse the journal from a receipt.
    let output: Vec<u8> = receipt
        .receipt
        .journal
        .decode()
        .expect("failed to decode journal output");

    assert_eq!(output.len(), 32 + 33);

    let hash = &output[..32];
    let point = &output[32..];

    println!("receipt journal output:");
    println!("  hash:  {}", hex::encode(hash));
    println!("  point: {}", hex::encode(point));

    // The receipt was verified at the end of proving, but the below code is an
    // example of how someone else could verify this receipt.
    println!("verifying receipt...");
    receipt.receipt.verify(PROVABLE_SHA256_DLOG_ID).unwrap();
    println!("OK");
}
```

Cargo.toml

```toml
[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "1.0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"
hex = { version = "0.4.3", default-features = false }
```

</details>

3. `cargo run .` -> Panics.

## Expected behavior

If the `k256` elliptic curve code should work with zkVM, the proof should be constructed successfully.

If `k256` is doing something wrong/disallowed by the zkVM, I should see some clear error telling me what/why so that I can help address it upstream. 
 

## Your Environment

- risc0-zkvm version: `0.20.1`
- Rust version: `rustc 1.76.0 (07dca489a 2024-02-04)`
- Platform/OS: Linux (Debian 12)

## Additional context

TODO:

- Does the prover work in dev mode?
- Does the prover work if no elliptic curve math is done, but k256 is still used? What if we only do finite field math (e.g. multiply the input secret) instead of point-scalar multiplication?
