### ISSUE TITLE
[Feature] CI: Include `rzup` in workflow

### ISSUE THREAD

**Issue by hmrtn** [risc0/risc0#1777]
## Feature
We should introduce CI tests for the recently added `rzup` installation scripts (#1774).

## Motivation
To test the installation process works as intended via `rzup` when changes occur to the scripts, or general install procedure.

## Implementation
There is a reference comment for adding a new job to the main workflow here: https://github.com/risc0/risc0/pull/1774#issuecomment-2091419475 

@morgangibbs87 alternatively pointed out these CI tests can be included in the [nightly](https://github.com/risc0/risc0/blob/main/.github/workflows/nightly.yml) workflow, or in the [scripts](https://github.com/risc0/risc0/tree/main/.github/scripts) workflow with something like this block: 
```
- name: Install rzup
  env:
    GITHUB_SHA: ${{ github.sha }}
  run: bash ./install
  working-directory: ./rzup

- name: Installs RISC Zero and Toolchain
  env:
    GITHUB_SHA: ${{ github.sha }}
  run: bash ./rzup
  working-directory: ./rzup
```

**Comment by morgangibbs87** [comment]
Forgot to add `shell` to the sample CI I gave. Without it you might get an error.

Corrected:

```
- name: Install rzup
  env:
    GITHUB_SHA: ${{ github.sha }}
  run: bash ./install
  shell: bash
  working-directory: ./rzup

- name: Installs RISC Zero and Toolchain
  env:
    GITHUB_SHA: ${{ github.sha }}
  run: bash ./rzup
  shell: bash
  working-directory: ./rzup
```
