### ISSUE TITLE
support guest programs published as independent crates

### ISSUE THREAD

**Issue by conduition** [risc0/risc0#2749]
### Is there an existing issue?

- [x] I have searched the existing issues

### Experiencing problems? Have you tried our Discord first?

- [x] This is not a support question.

### Motivation

I want to publish a reusable Rust library crate which uses several RISC0 proofs as part of its core functionality. Specifically, [this is the repo in question](https://github.com/conduition/zkcp).

However, Cargo does not allow inclusion of more than one `Cargo.toml` files inside a crate when publishing. It allows only one `Cargo.toml` file in crate root dir. All others are silently elided [even if you try to explicitly `include` them in the packaged crate](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields).

If i want to publish my library to `crates.io`, I first need to publish my RISC0 guest programs as crates on crates.io as well, and then somehow reference them from my main crate. 

### Request

Currently, [the RISC0 build code only works on guest program crates referenced by relative file path](https://github.com/risc0/risc0/blob/d29ba62a26d25963f360255c9f526deee3a691cc/risc0/build/src/lib.rs#L369-L377). There should be an option for callers to publish their guest programs to crates.io, and reference them in the `[package.metadata.risc0]` section of the crate being built.

### Solution

In addition to relative paths to crates, the RISC0 build command should also support a specifier which tells it to use published crates. For instance:

```toml
[package.metadata.risc0]
methods = ["./local_crate", "crates.io:remote-crate", "git:https://github.com/user/git-crate"]
```

Alternatively we might add a new TOML property specific to each crate's origin.

```toml
[package.metadata.risc0]
methods = ["./local_crate"]
methods_crates_io = ["remote-crate"]
methods_git = ["https://github.com/user/git-crate"]
```

Open questions:
- How to handle version specifiers and feature-flags on guest program crates?
- The main crate (the one declaring `[package.metadata.risc0]` should not need to directly depend on the guest program crate, as it's compiled independently by RISC0's toolchain. This means the RISC0 build script would have to independently download the crate with cargo, probably into a temp directory or a local cache.

Am willing to help sketch out and implement a solution but my time is quite limited at the moment.

### Are you willing to help with this request?

Yes!, Maybe... (I have elaborated on how above)
