### ISSUE TITLE
Template from `cargo-risczero` error `bytemuck_derive@1.9.2 requires rustc 1.84`

### ISSUE THREAD

**Issue by MarcusWentz** [risc0/risc0#3000]
### Is there an existing issue?

- [x] I have searched the existing issues

### Experiencing problems? Have you tried our Discord first?

- [x] This is not a support question.

### Description of bug

Error suggests the user is running
```shell
rustc 1.81.0-dev
```
while this Rust version it isn't installed globally
```rust
Compiling methods v0.1.0 (/Users/user/github/risc0_hello_world/methods)
test_template: Starting build for riscv32im-risc0-zkvm-elfbuild)                                                    
test_template: error: rustc 1.81.0-dev is not supported by the following package:
test_template:   bytemuck_derive@1.9.2 requires rustc 1.84
test_template: Either upgrade rustc or select compatible dependency versions with
test_template: `cargo update <name>@<current-ver> --precise <compatible-ver>`
test_template: where `<compatible-ver>` is the latest version supporting rustc 1.81.0-dev
test_template: 
error: failed to run custom build command for `methods v0.1.0 (/Users/user/github/risc0_hello_world/methods)`

Caused by:
  process didn't exit successfully: `/Users/user/github/risc0_hello_world/target/debug/build/methods-c94daa174a1ef093/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=RISC0_SKIP_BUILD
  Building guest package methods.test_template
  cargo:rerun-if-env-changed=RISC0_SKIP_BUILD
  Using rustc: /Users/user/.rustup/toolchains/risc0/bin/rustc
  cargo:rerun-if-env-changed=RISC0_RUST_SRC
  Building guest package: cargo build --target riscv32im-risc0-zkvm-elf
  cargo:rerun-if-env-changed=RISC0_BUILD_DEBUG
```

### Steps to reproduce

Install cargo crate cargo-risczero

```shell
cargo install cargo-risczero
```

Generate template

```shell
cargo risczero new project_name
```

Test run template

```shell
cargo run
```

Reference:

https://crates.io/crates/cargo-risczero

**Comment by MarcusWentz** [comment]
When I do
```shell
rustc --version
```
I get Rust version
```shell
rustc 1.84.0 (9fc6b4312 2025-01-07)
```
but the RISC Zero template after running
```shell
cargo run
```
still thinks I am using the following in the error log
```shell
rustc 1.81.0-dev
```
What might be causing this @bobbobbio ?

**Comment by bobbobbio** [comment]
It uses `1.81.0` to build the guest, that is why are you seeing that. We will soon release support for 1.85.0 for building guests, in the mean-time you can pin the version of `bytemuck_derive` to an older version in the guest's `Cargo.toml` to work around this issue.

**Comment by MarcusWentz** [comment]
@bobbobbio 

I don't see `bytemuck_derive` in file

```
methods/guest/Cargo.toml
```

which contains the following info

```toml
[package]
name = "project_name"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2.5", default-features = false, features = ['std'] }
```

however in file 

```
methods/guest/Cargo.lock
```

I see a section with `bytemuck_derive`

```toml
dependencies = [
 "bytemuck_derive",
]

[[package]]
name = "bytemuck_derive"
version = "1.9.2"
```

What version of `bytemuck_derive` should be used for stable support with Rust version 1.81.0 ?

**Comment by bobbobbio** [comment]
It should be a new line in your guest's `Cargo.toml` like `bytemuck_derive = "=1.8.1"`

**Comment by MarcusWentz** [comment]
I updated Cargo.toml in path

```
methods/guest/Cargo.toml
``` 

to include dependency `bytemuck_derive` with a set version 

```
bytemuck_derive = "=1.8.1"
```

which now looks like

```toml
[package]
name = "project_name"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2.5", default-features = false, features = ['std'] }
bytemuck_derive = "=1.8.1"
```

Now when I run 

```shell
cargo run
```

I get no errors. Thank you @bobbobbio for helping me fix this.
