### ISSUE TITLE
Feature Request: Add `Digest` compatible interface to risc0_zkvm_guest::sha2

### ISSUE THREAD

**Issue by preston-evans98** [risc0/risc0#691]
## Background
Currently, the accelerated [`sha256` function](https://docs.rs/risc0-zkvm/latest/risc0_zkvm/sha/trait.Sha256.html) uses a custom interface. This interface is incompatible with the [`Digest` trait](https://docs.rs/digest/latest/digest/trait.Digest.html), which is broadly used across the ecosystem. As a result, people who want to use the accelerated sha256 hasher need to fork and patch many of their dependencies. 

## Proposed Solution
Risc0 should maintain a fork of the [`sha2` crate](https://docs.rs/sha2/latest/sha2/type.Sha256.html) which uses the accelerator as the backend. This way, consumers could simply use a cargo `[patch.crates-io]` statement to replace the sha2 dependency in their guest code and all of its dependencies.

```toml
[package]
name = "my-risc0-project"

[dependencies]
sha2 = "0.10"
# ...

[patch.crates-io]
sha2 = { "https://github.com/risc0/sha2.git" } 
```
